### ISSUE TITLE
Problems with Local Server

### ISSUE THREAD

**Issue by damianlluch** [cboard-org/cboard-api#289]
Hi guys, I'm trying to build the back project locally and I'm getting this error:

What version of Node is running the back? I don't see anything specified in the readme.
Any readme of where I have to edit these files? are they necessary to build the API?

damiancastellilluch@damians-macbook-pro cboard-api % npm run start

> cboard-api@1.3.1 start /Users/damiancastellilluch/Documents/work/cboard-api
> node app.js

Sendgrid is configured as an email transport.
configured: true
temporary user model generated: true

/Users/damiancastellilluch/Documents/work/cboard-api/node_modules/passport-oauth2/lib/strategy.js:87
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                                 ^
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/damiancastellilluch/Documents/work/cboard-api/node_modules/passport-oauth2/lib/strategy.js:87:34)
    at new Strategy (/Users/damiancastellilluch/Documents/work/cboard-api/node_modules/passport-facebook/lib/strategy.js:56:18)
    at Object.<anonymous> (/Users/damiancastellilluch/Documents/work/cboard-api/api/passport/facebook.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions.js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at Module.patchedRequire (/Users/damiancastellilluch/Documents/work/cboard-api/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at Module.Hook._require.Module.require (/Users/damiancastellilluch/Documents/work/cboard-api/node_modules/require-in-the-middle/index.js:101:39)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/damiancastellilluch/Documents/work/cboard-api/app.js:20:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions.js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cboard-api@1.3.1 start: `node app.js`
npm ERR! Output status 1
npm ERR! 
npm ERR! Failed start script cboard-api@1.3.1.
npm ERR! This is probably not a problem with npm. There is probably additional log output above.

npm ERR! A complete log of this run can be found at:
¡npm ERR! /Users/damiancastellilluch/.npm/_logs/2023-04-23T15_47_03_217Z-debug.log

thank you very much!

**Comment by martinbedouret** [comment]
this is a local configuration issue. Closed.
